excute/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.testwsindex, name='index'),
    url(r'addhost/$', views.addhost, name='addhost'),
    url(r'testws/$', views.testws, name='testws'),
]

lyops/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ops/', include('ops.urls', namespace='ops')),
    url(r'^excute/', include('excute.urls', namespace='excute')),
]

ops/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'logout/$', views.logout, name='logout'),
    url(r'handle_login/$', views.handle_login, name='handle_login'),
    url(r'login/$', views.login, name='login'),
    url(r'handle_change/$', views.handle_change, name='handle_change'),
    url(r'check_password/$', views.check_password, name='check_password'),
    url(r'change/$', views.change, name='change'),

    url(r'userlist/copykey/$', views.copykey, name='copykey'),
    url(r'userlist/duser/$', views.duser, name='duser'),
    url(r'userlist/$', views.userlist, name='userlist'),
    url(r'adduser/handle_useradd/$', views.handle_useradd, name='handle_useradd'),
    url(r'adduser/$', views.adduser, name='adduser'),
    url(r'manager/check_project/$', views.check_project, name='check_project'),
    url(r'manager_modify/$', views.manager_modify, name='manager_modify'),
    url(r'manager/$', views.manager, name='manager'),
    url(r'commandlist/$', views.commandlist, name='commandlist'),
    url(r'sshkey/', views.sshkey, name='sshkey'),

]

excute/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Hosts(models.Model):
    '''host'''
    pub_ip = models.CharField(max_length=16, unique=True, verbose_name='公网ip')
    inner_ip = models.CharField(max_length=16, unique=True, verbose_name='内网ip')
    status_choices = (
        (0, u'new'),
        (1, u'up'),
        (2, u'cancel'),
        (3, u'known'),
    )
    status = models.PositiveSmallIntegerField(choices=status_choices, default=0, verbose_name='机器状态')
    create_time = models.DateTimeField()
    host_configuration = models.ForeignKey('Configuration')
    price = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    project_name = models.ForeignKey('Project', verbose_name='所属项目')


    def __str__(self):
        return self.inner_ip

    class Meta:
        verbose_name = u'主机表'
        verbose_name_plural = u'主机表'


class Configuration(models.Model):
    '''详细配置'''
    name = models.CharField(max_length=32, verbose_name='配置类型')
    specific_config = models.TextField(verbose_name='配置详情')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'主机配置表'
        verbose_name_plural = u'主机配置表'


class Tags(models.Model):
    '''
    标签信息
    '''
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'标签表'
        verbose_name_plural = u'标签表'


class Project(models.Model):
    '''项目表'''
    name = models.CharField(max_length=16, verbose_name='项目名称')
    note = models.TextField(verbose_name='备注')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'项目表'
        verbose_name_plural = u'项目表'


class Services(models.Model):
    '''部署服务表'''
    service_num = models.CharField(max_length=64, verbose_name='服务编号', blank=True, null=True)
    # uuid = models.CharField(max_length=64, verbose_name='服务唯一标识', blank=True, null=True)
    type_choices = (
        (0, u'DB'),
        (1, u'Redis'),
        (2, u'Serverlist'),
        (3, u'cobar/mycat'),
        (4, u'GM'),
        (5, u'Sfs'),
        (6, u'api'),
        (7, u'DB_backup'),
        (8, u'other'),
    )
    type = models.PositiveSmallIntegerField(choices=type_choices, verbose_name='服务类型')
    deploy_host = models.ForeignKey('Hosts', verbose_name='所属主机')
    deploy_time = models.DateTimeField(verbose_name='部署时间')
    version = models.CharField(max_length=8, verbose_name='软件版本', blank=True, null=True)
    port = models.IntegerField(verbose_name='服务监听端口', blank=True, null=True)
    dns_name = models.CharField(max_length=128, verbose_name='服务域名',blank=True, null=True)
    use_status_choices = (
        (0, u'备用'),
        (1, u'使用'),
    )
    use_status = models.PositiveSmallIntegerField(choices=use_status_choices, verbose_name='使用状态', default=1)
    flags = models.CharField(max_length=32, blank=True, null=True)
    install_way_choices = (
        (0, u'source'),
        (1, u'yum/rpm'),
        (2, u'docker'),
        (3, u'other'),
    )
    # to_db = models.ForeignKey('self', related_name='uuid', verbose_name='to_db', blank=True, null=True)
    # to_subordinate_db = models.ForeignKey('self', verbose_name='subordinate-db', blank=True, null=True)
    install_way = models.PositiveSmallIntegerField(choices=install_way_choices, verbose_name='安装方式')

    def __str__(self):
        return "%s-%s-%s" % (str(self.type), self.port, self.deploy_host)

    class Meta:
        verbose_name = u'部署服务表'
        verbose_name_plural = u'部署服务表'


class DBms(models.Model):
    '''db信息关系表'''
    main = models.ForeignKey(Services, verbose_name='主库')
    subordinate = models.OneToOneField(Services, related_name='uuid', verbose_name='从库')

    def __str__(self):
        return "%s-%s" % (self.main, self.subordinate)

    class Meta:
        verbose_name = u'db从主表'
        verbose_name_plural = u'db主从表'


class DBsfs(models.Model):
    '''db sfs信息表'''
    sfs = models.OneToOneField(Services, verbose_name='sfs')
    db = models.ForeignKey(DBms, verbose_name='数据库')

    def __str__(self):
        return "%s-%s" % (self.sfs, self.db)

    class Meta:
        verbose_name = u'sfsdb表'
        verbose_name_plural = u'sfsdb表'

excute/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
import sys
os.environ['DJANGO_SETTINGS_MODULE'] = 'lyops.settings'
import time
import commands
default_encoding = 'utf-8'
if sys.getdefaultencoding() != default_encoding:
    reload(sys)
    sys.setdefaultencoding(default_encoding)

from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from dwebsocket import require_websocket
from models import *
from ansi2html import Ansi2HTMLConverter
from playbooks.ansible_run import *

# Create your views here.
def index(request):
    page = request.GET['page']
    if page == 'host':
        status = request.GET.get('status', '0')
        if status == '4':
            hostlist = Hosts.objects.all().order_by('-create_time')
        else:
            hostlist = Hosts.objects.filter(status=status).order_by('-create_time')
        context = {
            'hostlist': hostlist,
        }
        return render(request, 'excute/host.html', context)
    elif page == 'service':
        type = request.GET['type']
        if type == '-1':
            service_list = Services.objects.all().order_by('-deploy_time')
        else:
            service_list = Services.objects.filter(type=type).order_by('-deploy_time')
        context = {
            'service_list': service_list,
        }
        return render(request, 'excute/service.html', context)

def addhost(request):
    data = json.loads(request.body)
    pub_ip = data['pub_ip']
    inner_ip = data['inner_ip']
    status = data['status']
    project_name = data['project_name']
    create_time = data['create_time']
    host_configuration = data['host_configuration']
    price = data['price']

    host = Hosts()
    host.inner_ip = inner_ip
    host.pub_ip = pub_ip
    host.status = status
    project_name = Project.objects.get(name=project_name)
    host.project_name = project_name
    host.create_time = create_time
    host_configuration = Configuration.objects.get(name=host_configuration)
    host.host_configuration = host_configuration
    host.price = price

    try:
        host.save()
        return JsonResponse({'result': 1})
    except (BaseException), e:
        print e
        return JsonResponse({'result': 0})

def testwsindex(request):
    return render(request, 'excute/websocket_test.html')

@require_websocket
def testws(request):
    conv = Ansi2HTMLConverter(inline=True)

    # message = request.websocket.wait()



    with open('/data/pycharm/python2_base/lyops/excute/playbooks/ansible-3.out', 'r') as f:
        while True:

            ansible_start_pid = commands.getstatusoutput('ps aux|grep ansible_start | grep -v grep')[1]
            if ansible_start_pid:
                while True:

                    content = f.readline()
                    if content:
                        message = b'%s' % content
                        request.websocket.send(conv.convert(message, full=False))
                    else:
                        time.sleep(1)
                        break
            else:
                while True:
                    content = f.readline()
                    if content:
                        message = b'%s' % content
                        request.websocket.send(conv.convert(message, full=False))
                    else:
                        try:
                            request.websocket.send(b'filenull')
                            message = request.websocket.wait()
                        except:
                            break
                break

        # for message in request.websocket:
        #     # f = open('/data/pycharm/python2_base/lyops/playbooks/ansible-3.out', 'r')
        #     request.websocket.send(message)  # 发送消息到客户端

templates/excute/host.html
{% extends 'excute/index.html' %}

{% block js2 %}
    <script type="text/javascript">
        $(function () {

            function GetRequest() {
                var url = location.search; //获取url中"?"符后的字串
                var theRequest = new Object();
                if (url.indexOf("?") != -1) {
                    var str = url.substr(1);
                    strs = str.split("&");
                    for(var i = 0; i < strs.length; i ++) {
                        theRequest[strs[i].split("=")[0]] = unescape(strs[i].split("=")[1]);
                    }
                }
                return theRequest;
            }

            var Request = new Object();
            Request = GetRequest();
            aa = Request['status'];
            $("#select_status").val(aa);

            $("#select_status").change(function () {
                var status = $(this).val();

                window.location.href = "/excute/?status="+status+"&page=host";



            });
        })
    </script>
{% endblock %}



{% block content2 %}

    <table class="table table-bordered">
      <span>选择主机状态:&nbsp</span>
      <select id='select_status' style="height: 26px;width: 100px;">
          <option value="0">new</option>
          <option value="1">up</option>
          <option value="2">cancel</option>
          <option value="3">unknown</option>
          <option value="4">ALL</option>

      </select>
      &nbsp&nbsp
      <span>搜索:&nbsp;</span>
      <input type="text">
      <br>
      <br>
      <thead>
        <tr>
          <th>公网IP</th>
          <th>内网IP</th>
          <th>机器状态</th>
          <th>注册时间</th>
          <th>主机配置</th>
          <th>价格</th>
          <th>所属项目</th>
        </tr>
      </thead>
      <tbody>

        {% for host in hostlist %}
        <tr>
          <td scope="row">{{ host.pub_ip }}</td>
          <td>{{ host.inner_ip }}</td>
          <td>{{ host.get_status_display }}</td>
          <td>{{ host.create_time }}</td>
          <td>{{ host.host_configuration }}</td>
          <td>${{ host.price }}/月</td>
          <td>{{ host.project_name }}</td>
        </tr>
        {% endfor %}

      </tbody>
    </table>


{% endblock %}

templates/excute/index.html
{% extends 'ops/index.html' %}


{% block title1 %}
hostlist
{% endblock %}

{% block js1 %}
    <script type="text/javascript" src="/static/js/csrftoken.js"></script>
    <script type="text/javascript">
        $(function () {

        })
    </script>

    {% block js2 %}{% endblock %}

{% endblock %}


{% block content1 %}
    <ol class="breadcrumb">
      <li class="active">主机管理</li>
      <li><a href="/excute/?type=-1&page=service">服务管理</a></li>
      <li><a href="#">批量执行</a></li>
      <li><a href="#">服务剧本</a></li>
    </ol>

    {% block content2 %}{% endblock %}



{% endblock %}

templates/excute/manage_host.html
{% extends 'excute/index.html' %}

{% block js2 %}

{% endblockd %}



{% block content2 %}

    <button type="button" class="btn btn-primary">（首选项）Primary</button>


{% endblock %}

templates/excute/service.html
{% extends 'excute/index.html' %}

{% block js2 %}
    <script type="text/javascript">
        $(function () {

            function GetRequest() {
                var url = location.search; //获取url中"?"符后的字串
                var theRequest = new Object();
                if (url.indexOf("?") != -1) {
                    var str = url.substr(1);
                    strs = str.split("&");
                    for(var i = 0; i < strs.length; i ++) {
                        theRequest[strs[i].split("=")[0]] = unescape(strs[i].split("=")[1]);
                    }
                }
                return theRequest;
            }

            var Request = new Object();
            Request = GetRequest();
            aa = Request['type'];
            $("#select_type").val(aa);

            $("#select_type").change(function () {
                var type = $(this).val();

                window.location.href = "/excute/?type="+type+"&page=service";



            });
        })
    </script>
{% endblock %}



{% block content2 %}

    <table class="table table-bordered">
      <span>选择主机状态:&nbsp</span>
      <select id='select_type' style="height: 26px;width: 100px;">

          <option value="0">DB</option>
          <option value="1">Redis</option>
          <option value="2">Serverlist/mycat</option>
          <option value="3">cobar/mycat</option>
          <option value="4">GM</option>
          <option value="5">Sfs</option>
          <option value="6">api</option>
          <option value="7">DB_backup</option>
          <option value="8">other</option>
          <option value="-1">ALL</option>

      </select>
      &nbsp&nbsp
      <span>搜索:&nbsp;</span>
      <input type="text">
      <br>
      <br>
      <thead>
        <tr>
          <th>服务编号</th>
          <th>服务类型</th>
          <th>所属主机</th>
          <th>部署状态</th>
          <th>软件版本</th>
          <th>监听端口</th>
          <th>服务域名</th>
          <th>使用状态</th>
          <th>安装方式</th>
        </tr>
      </thead>
      <tbody>

        {% for service in service_list %}
        <tr>
          <td scope="row">{{ service.service_num }}</td>
          <td>{{ service.get_type_display }}</td>
          <td>{{ service.deploy_host }}</td>
          <td>{{ service.deploy_time }}</td>
          <td>{{ service.version }}</td>
          <td>{{ service.port }}</td>
          <td><a>查看服务域名</a></td>
          <td>{{ service.get_use_status_display }}</td>
          <td>{{ service.get_install_way_display }}</td>
        </tr>
        {% endfor %}

      </tbody>
    </table>


{% endblock %}

templates/excute/testaaa.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title></title>
<style type="text/css">
.ansi2html-content { display: inline; white-space: pre-wrap; word-wrap: break-word; }
.body_foreground { color: #AAAAAA; }
.body_background { background-color: #000000; }
.body_foreground > .bold,.bold > .body_foreground, body.body_foreground > pre > .bold { color: #FFFFFF; font-weight: normal; }
.inv_foreground { color: #000000; }
.inv_background { background-color: #AAAAAA; }
.ansi1 { font-weight: bold; }
.ansi31 { color: #aa0000; }
.ansi32 { color: #00aa00; }
.ansi33 { color: #aa5500; }
.ansi35 { color: #E850A8; }
</style>
</head>
<body class="body_foreground body_background" style="font-size: normal;" >
<pre class="ansi2html-content">
PLAY [test yml] *********************************************************************************************************************************************

TASK [test cmd 1] *******************************************************************************************************************************************
<span class="ansi1 ansi35"> [WARNING]: Consider using file module with state=touch rather than running touch</span>
<span class="ansi1 ansi35"></span>
<span class="ansi33">changed: [192.168.146.132]</span>
<span class="ansi33">changed: [192.168.146.131]</span>

TASK [xx oo JJ] *********************************************************************************************************************************************
<span class="ansi33">changed: [192.168.146.131]</span>
<span class="ansi31">fatal: [192.168.146.132]: FAILED! =&gt; {"changed": true, "cmd": "ls /root/a.txt", "delta": "0:00:00.002577", "end": "2018-10-17 14:03:52.098361", "failed": true, "rc": 2, "start": "2018-10-17 14:03:52.095784", "stderr": "ls: 无法访问/root/a.txt: 没有那个文件或目录", "stderr_lines": ["ls: 无法访问/root/a.txt: 没有那个文件或目录"], "stdout": "", "stdout_lines": []}</span>

TASK [test cmd 3] *******************************************************************************************************************************************
<span class="ansi33">changed: [192.168.146.131]</span>

TASK [print the val1] ***************************************************************************************************************************************
<span class="ansi32">ok: [192.168.146.131] =&gt; {</span>
<span class="ansi32">    "changed": false, </span>
<span class="ansi32">    "msg": "master"</span>
<span class="ansi32">}</span>

TASK [print the val2] ***************************************************************************************************************************************
<span class="ansi32">ok: [192.168.146.131] =&gt; {</span>
<span class="ansi32">    "changed": false, </span>
<span class="ansi32">    "msg": "aa, bb"</span>
<span class="ansi32">}</span>
	to retry, use: --limit @/etc/ansible/playbooks/test.retry

PLAY RECAP **************************************************************************************************************************************************
<span class="ansi33">192.168.146.131</span>            : <span class="ansi32">ok=5   </span> <span class="ansi33">changed=3   </span> unreachable=0    failed=0
<span class="ansi31">192.168.146.132</span>            : <span class="ansi32">ok=1   </span> <span class="ansi33">changed=1   </span> unreachable=0    <span class="ansi31">failed=1   </span>


</pre>
</body>

</html>

templates/excute/websocket_test.html
<!DOCTYPE html>
<html>
<head>
    <title>django-websocket</title>
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script type="text/javascript">//<![CDATA[
        $(function () {
            $('#send_message').click(function () {

                var last_health;

                function keepalive(ws) {
                    var time = new Date();
                    if ((time.getTime() - last_health > 10000)) {
                        ws.close();
                        console.log('WebSocket closed');
                        //clearInterval(window.heartbeat_timer)
                    }
                }

                var socket = new WebSocket("ws://" + window.location.host + "/excute/testws/");
                socket.onopen = function () {
                    {#window.heartbeat_timer = setInterval(function () {keepalive(socket)}, 30000);#}
                    console.log('WebSocket open');//成功连接上Websocket
                    socket.send($('#message').val());//发送数据到服务端
                };
                socket.onmessage = function (e) {
                    {#var time = new Date();#}
                    {#last_health = time.getTime();#}
                    {#window.heartbeat_timer = setInterval(function () {keepalive(window.s)}, 30000);#}
                    {#console.log('message: ' + e.data);//打印服务端返回的数据#}
                    {#console.log(e.data);#}
                    if(e.data == 'filenull'){
                        console.log('WebSocket close');
                        socket.close();
                    }else{
                        $('.ansi2html-content').append('<p>' + e.data + '</p>');
                    }

                };

            });
        });
    //]]>
    </script>
    <style type="text/css">
    .ansi2html-content { display: inline; white-space: pre-wrap; word-wrap: break-word; }
    .body_foreground { color: #AAAAAA; }
    .body_background { background-color: #000000; }
    .body_foreground > .bold,.bold > .body_foreground, body.body_foreground > pre > .bold { color: #FFFFFF; font-weight: normal; }
    .inv_foreground { color: #000000; }
    .inv_background { background-color: #AAAAAA; }
    .ansi1 { font-weight: bold; }
    .ansi31 { color: #aa0000; }
    .ansi32 { color: #00aa00; }
    .ansi33 { color: #aa5500; }
    .ansi35 { color: #E850A8; }
    </style>
</head>
<body>
    <br>
    <input type="text" id="message" value="Hello, World!"/>
    <button type="button" id="send_message">发送 message</button>
    <h1>Received Messages</h1>
    <div id="messagecontainer">
        <pre class="ansi2html-content">
        </pre>
    </div>
</body>
</html>